BATOPT ERRP=ON

LKELOAD NETCLS
LKELOAD SNAPCLS
rem LKELOAD ENWDADRV
rem LKELOAD ENNEADRV

LKELOAD ENRTADEV

LKELOAD ARPCLS
LKELOAD IPSCLS
LKELOAD TCPCLS
LKELOAD UDPCLS
LKELOAD RCPCLS
LKELOAD XFPOCLS
LKELOAD XFPCLS
rem LKELOAD TNPCLS

rem ADDUNIT NET: UNIT=0 TYPE=EWDA IOREG=0x300 INT=15 MEM=0x0D0000
rem ADDUNIT NET: UNIT=0 TYPE=ENEA IOREG=0x300 INT=9
rem ADDUNIT NET: UNIT=0 TYPE=ENEA SLOT=19

ADDUNIT NET: UNIT=0 TYPE=ERTA SLOT=9

ADDUNIT SNAP: UNIT=0 NETDEV=NET0
DEVCHAR SNAP0: SAP=0FF-FF
rem DEVCHAR/Q SNAP0: SAP=0AA-AA
ADDUNIT ARP: UNIT=0 SNAPDEV=SNAP0
DEVCHAR/Q ARP0: ETYPE=8-6

ADDUNIT IPS: UNIT=0 SNAPDEV=SNAP0
DEVCHAR/Q IPS0: CHKSUMH=FULL

DEVCHAR/Q IPS0: ETYPE=8-0 ARPDEV=ARP0
DEVCHAR/Q IPS0: IPADDR=10.3.0.1 SUBMASK=0FF-0-0-0
DEVCHAR/Q IPS0: DOMAIN=JRG2.ALLEGROSYS.COM 
DEVCHAR/Q IPS0: DRT1ADDR=10.0.0.1

ADDUNIT TCP: UNIT=0 IPSDEV=IPS0

DEVCHAR/q TCP0 IPPROT=6
ADDUNIT UDP UNIT=0 IPSDEV=IPS0
DEVCHAR/q UDP0 IPPROT=17
ADDUNIT RCP UNIT=0 UDPDEV=UDP0
DEVCHAR/Q RCP0 ACCESS=LANA

ADDUNIT XFPO UNIT=0 RCPDEV=RCP0

SYMBIONT XFPOSRV
SERVER XFPOSRV ADD INS=1 DEV=RCP0: NUMCON=1000

ADDUNIT XFP UNIT=0 TCPDEV=TCP0

SYMBIONT XFPSRV
SERVER XFPSRV ADD INS=1 TCPDEV=TCP0: CLIENT=1000

rem LKELOAD TLNACLS
rem ADDUNIT TLN UNIT=0 TCPDEV=TCP0
rem DEVCHAR TLN0A SESSION=YES

LKELOAD PCNCLS
ADDUNIT PCN UNIT=1
DEVCHAR PCN1 SESSION=YES PASSWORD=abcd#
SYMBIONT TLNSRV TLNDEV=TCP0

SYMBIONT FTPSRV
SERVER FTPSRV ADD INS=1 DEV=TCP0

SYMBIONT UDFSRV
SERVER /SYSLOG /LOG=abc.log UDFSRV ADD INS=1 DEV=UDP0: PORT=3002 GROUP=USER
SERVER /SYSLOG /LOG=abc.log UDFSRV MODIFY INS=1 MASK=255.255.255.255 ADD=10.3.0.1
SERVER /SYSLOG /LOG=abc.log UDFSRV MODIFY INS=1 MASK=255.255.255.255 ADD=10.3.0.2
SERVER /SYSLOG /LOG=abc.log UDFSRV MODIFY INS=1 MASK=255.255.255.255 ADD=10.5.0.3
SERVER /SYSLOG /LOG=abc.log UDFSRV MODIFY INS=1 MASK=255.255.255.255 ADD=10.2.0.1
