//++++
// This software is in the public domain.  It may be freely copied and used
// for whatever purpose you see fit, including commerical uses.  Anyone
// modifying this software may claim ownership of the modifications, but not
// the complete derived code.  It would be appreciated if the authors were
// told what this software is being used for, but this is not a requirement.

//   THIS SOFTWARE IS PROVIDED BY THE AUTHORS "AS IS" AND ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
//   OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
//   TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//   USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//----

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <xos.h>
#include <xossvc.h>
#include <xosrun.h>
#include <xostime.h>
#include <xoserrmsg.h>
#include <runread.h>

// This program reads a .BIN file (generated by RUN2BIN or by dumping a disk
//   block) containing a disk boot block (512 bytes) and generates a text file
//   containing the contents of the boot block as the specification for a
//   uchar array. The name of the array is the same as the name of the output
//   file, which must be specified without an extension. An extension of ".c"
//   is added. The input file must also be specified without an extension and
//   an extension of ".run" is added.

// Command format is:
//		makebtbk infile outfile include
//   The input file is infile.run and the output file is outfile.c.

char prgname[] = "MAKEDATA";

static void fail(char *str1, long code, char *str2);


int main(
    int   argc,
    char *argv[])

{
	FILE    *ofile;
	char    *cpnt;
	uchar   *dpnt;
	RUNHEAD  runhead;
	RUNSEG   seghead;
	RUNMSECT mshead;
	int      cnt;
	uchar    buffer[100];

	if (argc != 5 && argc != 4)
	{
		fputs("? MAKEDATA: Command error, correct usage is:\n"
			  "              MAKEDATA infile outfile name {delay}\n", stderr);
		exit (1);
	}
	if (argc == 5 && (cnt = atol(argv[4])) > 0)
		svcSchSuspend(NULL, cnt * ST_MILLISEC);

	// Open the input file and read its first msect

	if (!runreadopen(argv[1], &runhead, sizeof(runhead), fail))
		exit (1);
	if (!runreadgetsegheader(&seghead, sizeof(seghead)))
		exit (1);
	if (!runreadgetmsectheader(&mshead, sizeof(mshead)))
		exit (1);
	if ((dpnt = runreadmsect(&mshead, 1)) == NULL)
		exit (1);
	runreadclose();
	if ((ofile = fopen(argv[2], "w")) == NULL)
		femsg2(prgname, "Cannot create output file", -errno, NULL);
	printf("MAKEDATA: Array size is %d byte%s\n", mshead.alloc,
			(mshead.alloc == 1) ? "" : "s");
	if (fprintf(ofile, "// This file was created by MAKEDATA from %s\n\n"
				"uchar %s[%d] =\n", argv[1], argv[3], mshead.alloc) < 0)
		femsg2(prgname, "Error writing to bootblk.c", -errno, NULL);
	buffer[0] = '{';
	cpnt = buffer + 1;
	do
	{
		*cpnt++ = '\t';
		if ((cnt = mshead.alloc) > 16)
			cnt = 15;	
		mshead.alloc -= cnt;
		do
		{
			cpnt += sprintf(cpnt, "0x%02X,", *dpnt++);
		} while (--cnt > 0);
		if (mshead.alloc == 0)			// Finished?
			cpnt--;						// Yes - remove the last comma
		cpnt[0] = '\n';
		cpnt[1] = 0;
		if (fputs(buffer, ofile) < 0)
			femsg2(prgname, "Error writing to bootblk.c", -errno, NULL);
		cpnt = buffer;
	} while (mshead.alloc > 0);
	if (fputs("};\n", ofile) < 0)
		femsg2(prgname, "Error writing to bootblk.c", -errno, NULL);
	if (fclose(ofile) < 0)
		femsg2(prgname, "Error closing bootblk.c", -errno, NULL);
	fputs("MAKEDATA: Finished\n", stdout);
	return (0);
}


static void fail(
	char *str1,
	long  code,
	char *str2)
{
    femsg2(prgname, str1, code, str2);
}
